osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 10
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- if [[ "$TRAVIS_TAG" == "" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then npm --no-git-tag-version version prerelease; fi
- yarn run build
deploy:
  skip_cleanup: true
  provider: script
  script: yarn dist
  on:
    tags: true
branches:
  only:
  - master
  - /^greenkeeper/.*$/
