osx_image: xcode8.3
sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
matrix:
  include:
  - os: osx
  - os: linux
cache:
  yarn: true
script:
- yarn dist
deploy:
  skip_cleanup: true
  provider: releases
  on:
    tags: true
branches:
  only:
  - master
  - /^greenkeeper/.*$/
