version: 0.1.{build}

environment:
  matrix:
    - platform: x64
    - nodejs_version: 10

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set CI=true
  - yarn

build_script:
  - yarn build

on_success:
  - ps: Get-ChildItem .\build\*.exe | % { Push-AppveyorArtifact $_.FullName }

test_script:
  - yarn dist
