version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - set CI=true
  - yarn
  - node --version

build_script:
  - yarn build

on_success:
  - ps: Get-ChildItem .\build\*.exe | % { Push-AppveyorArtifact $_.FullName }  

test: off
