version: '{build}'

environment:
  matrix:
    - platform: x64

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt msa_digicert_CI.p12.enc -secret %CertSecret%
  - sh: ./appveyor-tools/secure-file -decrypt msa_digicert_CI.p12.enc -secret $CertSecret
  - ps: Install-Product node 10 x64
  - set CI=true
  - yarn

build: off

on_success:
  - ps: Get-ChildItem .\build\*.exe | % { Push-AppveyorArtifact $_.FullName }

test_script:
  - yarn dist
