name: Linux Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["12"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@v2
        name: Upload AppImage
        with:
          path: dist_electron/*.AppImage

      - uses: actions/upload-artifact@v2
        name: Upload Snap
        with:
          path: dist_electron/*.snap

      - uses: actions/upload-artifact@v2
        name: Upload deb
        with:
          path: dist_electron/*.deb

      - uses: actions/upload-artifact@v2
        name: Upload rpm
        with:
          path: dist_electron/*.rpm
