name: Linux Build
on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 11
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn
      env:
        CI: true
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn dist
      env:
        CI: true
    - uses: actions/upload-artifact@master
      with:
        name: WeakAuras-Companion-CI
        path: build/
