name: Linux Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["12"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        id: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run dist:pr

      - uses: actions/upload-artifact@v2
        name: Upload AppImage
        with:
          path: dist_electron/*.AppImage

      - uses: actions/upload-artifact@v2
        name: Upload Snap
        with:
          path: dist_electron/*.snap

      - uses: actions/upload-artifact@v2
        name: Upload deb
        with:
          path: dist_electron/*.deb

      - uses: actions/upload-artifact@v2
        name: Upload rpm
        with:
          path: dist_electron/*.rpm
