name: macOS Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node: ["12"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        id: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@v2
        name: Upload DMG
        with:
          path: dist_electron/*.dmg
