name: Windows Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node: ["10", "12"]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: yarn
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn dist
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      - uses: actions/upload-artifact@master
        with:
          name: WeakAuras-Companion-CI-Node${{ matrix.node }}
          path: build/
